WHITESPACE = _{ " " | "\t" | "\n" }
COMMENT    = _{ "--" ~ (!"\n" ~ ANY)* ~ "\n" }
program    = _{ SOI ~ ((assignment | application | term) ~ ";"?)* ~ EOI }
assignment =  { variable ~ "=" ~ (application | term) }
// Lambda calculus
term        = _{ abstraction | "(" ~ application ~ ")" | variable | "(" ~ term ~ ")" }
abstraction =  { ("\\" | "λ") ~ variable ~ "." ~ term }
application =  { term ~ term+ }
variable    = @{ ASCII_ALPHANUMERIC+ ~ "'"* }
